#!/usr/bin/env php
<?php
/**
 * Install tipsy archive into Dynacase context dir
 *
 * @author Anakeen 2013
 */
$WIFF_ROOT = getenv("WIFF_ROOT");
if ($WIFF_ROOT === false) {
    print "WIFF_ROOT environment variable is not set!\n";
    exit(1);
}

$WIFF_CONTEXT_ROOT = getenv("WIFF_CONTEXT_ROOT");
if ($WIFF_CONTEXT_ROOT === false) {
    print "WIFF_CONTEXT_ROOT environment variable not set!\n";
    exit(1);
}

set_include_path(get_include_path() . PATH_SEPARATOR . $WIFF_CONTEXT_ROOT . PATH_SEPARATOR . "$WIFF_ROOT/include");

include_once('WHAT/Lib.System.php');

$ck_tgz = $argv[1];
if ($ck_tgz === NULL) {
    print sprintf("Missing tipsy archive argument\n");
    exit(1);
}

$ck_tgz = realpath($ck_tgz);
if (!is_file($ck_tgz)) {
    print sprintf("Tipsy archive not found at '%s'\n", $ck_tgz);
    exit(1);
}

$ret = chdir($WIFF_CONTEXT_ROOT);
if ($ret === false) {
    print sprintf("Could not change directory to '%s'\n", $WIFF_CONTEXT_ROOT);
    exit(1);
}

$tmpfile = LibSystem::tempnam(null, 'tipsy_untar');
if ($tmpfile === false) {
    print sprintf("Could not create temporary file\n");
    exit(1);
}

$tempdir = basename($tmpfile);
$ret = mkdir($tempdir);
if ($ret === false) {
    print sprintf("Could not create temporary directory '%s'\n", $tempdir);
    @unlink($tmpfile);
    exit(1);
}

// Unpack archive in tempdir
$cmd = sprintf('tar -C %s -zxf %s > %s 2>&1', escapeshellarg($tempdir), escapeshellarg($ck_tgz),
    escapeshellarg($tmpfile));
system($cmd, $ret);

$output = file_get_contents($tmpfile);
@unlink($tmpfile);

if ($ret !== 0) {
    print sprintf("Error %s: %s\n", $cmd, $output);
    exit(1);
}

// Set directory/files rights
$cmd = sprintf('find %s -type d -exec chmod 0755 {} \; > /dev/null 2>&1', escapeshellarg($tempdir));
system($cmd, $ret);
if ($ret !== 0) {
    print sprintf("Error setting rights on directories\n");
    exit(1);
}
$cmd = sprintf('find %s -type f -exec chmod 0644 {} \; > /dev/null 2>&1', escapeshellarg($tempdir));
system($cmd, $ret);
if ($ret !== 0) {
    print sprintf("Error setting rights on files\n");
    exit(1);
}

// Search for a /jquery-ui/ subdir in the unpacked archive
$fh = opendir($tempdir);
if ($fh === false) {
    print sprintf("Error opening temporary directory '%s'\n", $tempdir);
    exit(1);
}

$tipsy_subdir = 'lib/tipsy/';
// Create jquery-ui dir if it does not exists
if (!is_dir($tipsy_subdir)) {
    $ret = mkdir($tipsy_subdir);
    if ($ret === false) {
        print sprintf("Could not create '$tipsy_subdir' directory\n");
        exit(1);
    }
}

// Copy new jquery-ui files over existing jquery-ui directory
$cmd = sprintf('cp -r %s/* %s', escapeshellarg($tempdir), escapeshellarg($tipsy_subdir));
system($cmd, $ret);

if ($ret !== 0) {
    print sprintf("Error copying tipsy files (%s)\n", $cmd);
    exit(1);
}

// Cleanup tempdir
$cmd = sprintf('rm -Rf %s', escapeshellarg($tempdir));
system($cmd, $ret);

exit(0);

?>

